# app/models/quotation.py
from sqlalchemy import Column, Integer, String, CHAR, VARCHAR, NUMERIC, TIMESTAMP
from sqlalchemy.ext.declarative import declarative_base

Base = declarative_base()


class Quotation(Base):
    __tablename__ = "quotation"

    id = Column(Integer, primary_key=True, index=True)
    quotation_id = Column(CHAR(10), nullable=False)
    quotation_branch_no = Column(CHAR(3), nullable=False)
    quotation_sfid = Column(CHAR(18), nullable=False)
    quotation_name = Column(VARCHAR(80))
    quotation_text = Column(VARCHAR(40), nullable=False)
    expected_order_sfid = Column(CHAR(18), nullable=False)
    sales_office = Column(CHAR(40))
    sales_office_name = Column(VARCHAR(40))
    sales_group = Column(CHAR(40))
    sales_group_name = Column(VARCHAR(40))
    sales_user_id = Column(CHAR(40))
    business_user_id = Column(CHAR(40))
    sales_organization = Column(CHAR(40))
    sales_organization_name = Column(VARCHAR(100))
    quotation_pattern = Column(CHAR(1), nullable=False)
    opportunity_flg = Column(CHAR(1))
    currency_category = Column(CHAR(1))
    quotation_amount_jpy = Column(Integer)
    quotation_amount_usd = Column(NUMERIC(18, 2))
    machine_service_sales_date_plan = Column(TIMESTAMP)
    terms_contract_start_date = Column(TIMESTAMP)
    terms_contract_end_date = Column(TIMESTAMP)
    status_cpq_id = Column(VARCHAR(2))
    order_recipient_id = Column(CHAR(10))
    quotation_start_date = Column(TIMESTAMP)
    quotation_expiration_date = Column(TIMESTAMP)
    supplier_quotation_expiration_date = Column(TIMESTAMP)
    maintenance_contract_id = Column(CHAR(10))
    individual_contract_no = Column(CHAR(25))
    non_regulated_supplier = Column(CHAR(1))
    compliance_flg = Column(CHAR(1))
    profit_rate = Column(NUMERIC(3, 1))
    machine_forecast_amount = Column(Integer)
    contract_forecast_amount = Column(Integer)
    quotation_type_010 = Column(CHAR(1))
    quotation_type_020 = Column(CHAR(1))
    quotation_type_030 = Column(CHAR(1))
    quotation_type_040 = Column(CHAR(1))
    quotation_type_050 = Column(CHAR(1))
    quotation_type_060 = Column(CHAR(1))
    quotation_type_070 = Column(CHAR(1))
    quotation_type_080 = Column(CHAR(1))
    quotation_type_090 = Column(CHAR(1))
    quotation_type_100 = Column(CHAR(1))
    quotation_type_110 = Column(CHAR(1))
    quotation_type_120 = Column(CHAR(1))
    seal_type_id = Column(CHAR(3))
    in_charge_name = Column(VARCHAR(100))
    maintenance_box_id = Column(CHAR(12))
    vbeln = Column(VARCHAR(40))
    contstart_date = Column(TIMESTAMP)
    contend_date = Column(TIMESTAMP)
    quotation_id_from = Column(CHAR(10))
    quotation_branch_no_from = Column(CHAR(3))
    quotation_date = Column(TIMESTAMP)
    delivery_address_memo = Column(VARCHAR(255))
    billing_address_memo = Column(VARCHAR(255))
    sava_memo = Column(VARCHAR(255))
    special_remarks = Column(VARCHAR(255))
    profit_rate_ex_lease = Column(NUMERIC(3, 1))
    machine_forecast_amount_ex_lease = Column(Integer)
    contract_forecast_amount_ex_lease = Column(Integer)
    invalid_flag = Column(CHAR(1))
    profit_rate_machine = Column(NUMERIC(3, 1))
    profit_rate_period_ex_lease = Column(NUMERIC(3, 1))
    bcntrctno = Column(CHAR(20))
    bill_cond = Column(VARCHAR(72))
    cntform = Column(CHAR(1))
