
# app/models/quotation_detail.py

from sqlalchemy import Column, Integer, String, CHAR, VARCHAR, NUMERIC, TIMESTAMP
from sqlalchemy.ext.declarative import declarative_base

Base = declarative_base()


class QuotationDetail(Base):
    __tablename__ = "quotation_detail"

    id = Column(Integer, primary_key=True, index=True)
    quotation_table_id = Column(Integer, nullable=False)
    quotation_id = Column(CHAR(10), nullable=False)
    quotation_branch_no = Column(CHAR(3), nullable=False)
    quotation_detail_id = Column(Integer, nullable=False)
    quotation_type = Column(CHAR(1), nullable=False)
    detail_type = Column(CHAR(1), nullable=False, default='1')
    change_time = Column(TIMESTAMP)
    registration_time = Column(TIMESTAMP)
    product_id = Column(CHAR(40))
    product_name = Column(CHAR(40))
    unit_price = Column(Integer)
    cost_price = Column(Integer)
    rate_of_cost_price = Column(Integer)
    rate_of_cost = Column(Integer)
    quotation_price = Column(Integer)
    total_cost_amount = Column(Integer)
    process_type = Column(CHAR(40))
    quantity = Column(Integer)
    reason_for_rejection = Column(CHAR(40))
    currency_classification_of_amount_provided = Column(CHAR(2))
    currency_classification_of_cost = Column(CHAR(2))
    counter1_for_confirmation = Column(CHAR(40))
    counter2_for_confirmation = Column(CHAR(40))
    compliance_check_remarks_column = Column(VARCHAR(100))
    intangible_flag = Column(CHAR(1))
    method_of_provision = Column(CHAR(40))
    contract_start_date = Column(TIMESTAMP)
    contract_end_date = Column(TIMESTAMP)
    purchase_request_approval_chk_flg = Column(CHAR(1))
    purchase_request_comments = Column(VARCHAR(100))
    shipping_method = Column(CHAR(40))
    fund_recognition_number = Column(VARCHAR(40))
    perform_id = Column(CHAR(10))
    cisco_vendor_support = Column(CHAR)
    arrangement_date = Column(TIMESTAMP)
    remarks = Column(VARCHAR(50))
    maker_model = Column(CHAR(40))
    quotation_date = Column(TIMESTAMP)
    zlifnr = Column(VARCHAR(10), nullable=False)
    werks = Column(CHAR(4))
    supplier_quotation_expiration_date = Column(TIMESTAMP)
    statement_category = Column(CHAR(10))
    zdeal_id = Column(CHAR(15), nullable=False)
    zdiscount = Column(NUMERIC(15, 4))
    sales_date_plan = Column(TIMESTAMP)
    std_price = Column(Integer)
    print_std_price = Column(Integer)
    disc_rate = Column(NUMERIC(3, 1))
    zmaker_product_code = Column(CHAR(40))
    service_std_id = Column(CHAR(10))
    zprf = Column(NUMERIC(3, 1))
